name: Actions Workflow

# on: [push, pull_request]
on:
  push:
  pull_request: 
    types: [closed, opened, assigned, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Learn env variables & commands
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA # to get CURRENT GITHUB COMMIT iD
          echo $GITHUB_REPOSITORY 
          echo $GITHUB_WORKSPACE #WORKSPACE DIRECTORY
          echo "${{github.token}}" #token to access repository
          

      - name: Simple Js Action
        id: greet
      # can use an action in present dir or a published repo
      # can use branch name, commit id or version to refer to which version of repo to use
        uses: actions/hello-world-javascript-action@v1
        with: 
          # to give inputs
          who-to-greet: Rev
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"