name: Actions Workflow

# on: [push, pull_request]
on:
  # filters
  push:
    branches:
      - master
      - 'feat/*' # matches feat/A, feat/b etc. 
                 # won't match feat/x/y
      - 'feat/**'   # matches feat/x/y
      - '!feat/c' # to ignore this specific branch
    # only one of branches or branches-ignore can be used at a time  
    # branches-ignore:
    #   - test
    tags-ignore: # also have tags
      - v0.*
    paths-ignore: # also paths-ignore
      - 'docs/**'
      - '**.js'

  #schedule:
  #  - cron: "*/10 * * * *" 
  #  - cron: "1-59/12 * * * *"
  pull_request: 
    types: [closed, opened, assigned, reopened]
  repository_dispatch:
    types: [build]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get dispatch params
        run: echo ${{ github.event.client_payload.env}}
      - name: Learn env variables & commands
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA # to get CURRENT GITHUB COMMIT iD
          echo $GITHUB_REPOSITORY 
          echo $GITHUB_WORKSPACE #WORKSPACE DIRECTORY
          echo "${{github.token}}" #token to access repository
          

      - name: Simple Js Action
        id: greet
      # can use an action in present dir or a published repo
      # can use branch name, commit id or version to refer to which version of repo to use
        uses: actions/hello-world-javascript-action@v1
        with: 
          # to give inputs
          who-to-greet: Rev
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"